language : node_js
node_js : 
  - 14.15.0
cache: yarn

before_install:
install:
  - yarn install

before_script:

# //all build process
script:
  - yarn test
  - yarn run build
after_success:
after_failure:
after_script:
before_deploy:
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github
  on:
    branch: dev
after_deploy: