version: '3'

services: 
  react-app:
    image: react-app
    stdin_open: true
    ports: 
      -"3000:3000"
  api-server:
    image: api-server
    ports: 
      -"7000:7000"
    depends_on: 
      -mongo
  mongo:
    image: mongo-app
    networks: 
      -mern-app
    volumes: 
      -mongo-data:/data/db

networks: 
  mern-app:
    driver: bridge

volumes: 
  mongo-data:
    driver: local